// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type JarMembership struct {
	ID       int32            `db:"id" json:"id"`
	JarID    int32            `db:"jar_id" json:"jar_id"`
	UserID   int32            `db:"user_id" json:"user_id"`
	Role     string           `db:"role" json:"role"`
	JoinedAt pgtype.Timestamp `db:"joined_at" json:"joined_at"`
}

type Offense struct {
	ID            int32            `db:"id" json:"id"`
	JarID         int32            `db:"jar_id" json:"jar_id"`
	OffenseTypeID int32            `db:"offense_type_id" json:"offense_type_id"`
	ReporterID    int32            `db:"reporter_id" json:"reporter_id"`
	OffenderID    int32            `db:"offender_id" json:"offender_id"`
	Notes         pgtype.Text      `db:"notes" json:"notes"`
	CostOverride  pgtype.Numeric   `db:"cost_override" json:"cost_override"`
	Status        string           `db:"status" json:"status"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type OffenseType struct {
	ID          int32            `db:"id" json:"id"`
	JarID       int32            `db:"jar_id" json:"jar_id"`
	Name        string           `db:"name" json:"name"`
	Description pgtype.Text      `db:"description" json:"description"`
	CostAmount  pgtype.Numeric   `db:"cost_amount" json:"cost_amount"`
	IsActive    bool             `db:"is_active" json:"is_active"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	CostUnit    pgtype.Text      `db:"cost_unit" json:"cost_unit"`
}

type Payment struct {
	ID         int32            `db:"id" json:"id"`
	OffenseID  int32            `db:"offense_id" json:"offense_id"`
	UserID     int32            `db:"user_id" json:"user_id"`
	Amount     pgtype.Numeric   `db:"amount" json:"amount"`
	ProofType  pgtype.Text      `db:"proof_type" json:"proof_type"`
	ProofUrl   pgtype.Text      `db:"proof_url" json:"proof_url"`
	Verified   bool             `db:"verified" json:"verified"`
	VerifiedBy pgtype.Int4      `db:"verified_by" json:"verified_by"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type TipJar struct {
	ID          int32            `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Description pgtype.Text      `db:"description" json:"description"`
	InviteCode  string           `db:"invite_code" json:"invite_code"`
	CreatedBy   int32            `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID        int32            `db:"id" json:"id"`
	Email     string           `db:"email" json:"email"`
	Name      string           `db:"name" json:"name"`
	Avatar    pgtype.Text      `db:"avatar" json:"avatar"`
	GoogleID  string           `db:"google_id" json:"google_id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
