// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateJarMembership(ctx context.Context, arg CreateJarMembershipParams) (JarMembership, error)
	CreateOffense(ctx context.Context, arg CreateOffenseParams) (Offense, error)
	CreateOffenseType(ctx context.Context, arg CreateOffenseTypeParams) (CreateOffenseTypeRow, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateTipJar(ctx context.Context, arg CreateTipJarParams) (TipJar, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateOffenseType(ctx context.Context, id int32) (DeactivateOffenseTypeRow, error)
	DeleteJarMembership(ctx context.Context, arg DeleteJarMembershipParams) error
	DeleteTipJar(ctx context.Context, id int32) error
	GetJarBalancesByUnit(ctx context.Context, jarID int32) ([]GetJarBalancesByUnitRow, error)
	GetJarMembership(ctx context.Context, arg GetJarMembershipParams) (JarMembership, error)
	GetOffense(ctx context.Context, id int32) (Offense, error)
	GetOffenseType(ctx context.Context, id int32) (GetOffenseTypeRow, error)
	GetPayment(ctx context.Context, id int32) (Payment, error)
	GetTipJar(ctx context.Context, id int32) (TipJar, error)
	GetTipJarByInviteCode(ctx context.Context, inviteCode string) (TipJar, error)
	GetUserBalanceInJar(ctx context.Context, arg GetUserBalanceInJarParams) (interface{}, error)
	GetUserBalancesByUnitInJar(ctx context.Context, arg GetUserBalancesByUnitInJarParams) ([]GetUserBalancesByUnitInJarRow, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	IsUserJarAdmin(ctx context.Context, arg IsUserJarAdminParams) (bool, error)
	IsUserJarMember(ctx context.Context, arg IsUserJarMemberParams) (bool, error)
	ListAllOffenseTypesForJar(ctx context.Context, jarID int32) ([]ListAllOffenseTypesForJarRow, error)
	ListJarMembers(ctx context.Context, jarID int32) ([]ListJarMembersRow, error)
	ListOffenseTypesForJar(ctx context.Context, jarID int32) ([]ListOffenseTypesForJarRow, error)
	ListOffensesForJar(ctx context.Context, arg ListOffensesForJarParams) ([]ListOffensesForJarRow, error)
	ListPaymentsForOffense(ctx context.Context, offenseID int32) ([]Payment, error)
	ListPaymentsForUser(ctx context.Context, arg ListPaymentsForUserParams) ([]ListPaymentsForUserRow, error)
	ListPendingOffensesForUser(ctx context.Context, offenderID int32) ([]ListPendingOffensesForUserRow, error)
	ListTipJarsForUser(ctx context.Context, userID int32) ([]TipJar, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (JarMembership, error)
	UpdateOffenseStatus(ctx context.Context, arg UpdateOffenseStatusParams) (Offense, error)
	UpdateOffenseType(ctx context.Context, arg UpdateOffenseTypeParams) (UpdateOffenseTypeRow, error)
	UpdateTipJar(ctx context.Context, arg UpdateTipJarParams) (TipJar, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	VerifyPayment(ctx context.Context, arg VerifyPaymentParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
